name: social_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cloud_firestore:
  firebase_auth:
  firebase_storage:
  firebase_core:
  image_picker:
  google_fonts:
  path_provider:
  video_player:
  intl:
  file_picker:
  video_compress:
  timeago:
  image:
  esys_flutter_share:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
